# Site settings
title: VIAJEXPLORER
description: 'Explora rutas turísticas, consejos de viaje y experiencias auténticas en ViajeXplorer. Desde los Alpes Suizos hasta Roma y la Toscana, te ofrecemos guías detalladas, recomendaciones de restaurantes, alojamiento asequible y actividades de aventura. Convierte cada viaje en una experiencia única con nuestra comunidad de exploradores.'
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://viajexplorer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/viajexplorer.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file



# Author settings
author: Javier Coco Gómez # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Engineer.

# Contact links
email: javiercg@usal.es # Add your Email address
phone: 666 666 666 # Add your Phone number
website: https://viajexplorer.github.io # Add your website
github: viajexplorer # Add your Github handle
twitter: '' # Add your Twitter handle
stackoverflow: stackoverflow # Add your stackoverflow account


# Tracker
analytics: G-6XVTPYB1YC
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true


# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  #- jekyll-compress

#assets:
 # css:
#    style: compressed
 #  js:
 #    style: compressed

#  - name: Web Pre-Processor
#     uses: tinpotnick/webpreprocessor@v1.13
            


include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
