# Site settings
title: VIAJEXPLORER
description: 'Descubre las mejores rutas turísticas, consejos de viaje y experiencias auténticas en nuestro blog. Desde los majestuosos Alpes Suizos hasta la histórica Roma y los encantadores pueblos de la Toscana, te ofrecemos guías detalladas para que disfrutes al máximo de cada destino. Encuentra recomendaciones de restaurantes locales, alojamiento asequible y actividades de aventura para cada tipo de viajero. Únete a nuestra comunidad de exploradores y convierte cada viaje en una experiencia inolvidable con ViajeXplorer."
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://viajexplorer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/viajexplorer.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file



# Author settings
author: Javier Coco Gómez # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Engineer.

# Contact links
email: javiercg@usal.es # Add your Email address
phone: # Add your Phone number
website: https://viajexplorer.github.io # Add your website
linkedin: amaynez # Add your Linkedin handle
github: amaynez # Add your Github handle
twitter: '' # Add your Twitter handle
stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-6XVTPYB1YC
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-compress

#assets:
 # css:
#    style: compressed
 #  js:
 #    style: compressed

#  - name: Web Pre-Processor
#     uses: tinpotnick/webpreprocessor@v1.13
            


include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
